//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class iQuranResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal iQuranResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.iQuranResources", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        internal static string ActiveHeader {
            get {
                return ResourceManager.GetString("ActiveHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New iQuran.
        /// </summary>
        internal static string AddNewiQuranHeader {
            get {
                return ResourceManager.GetString("AddNewiQuranHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Sura to this version.
        /// </summary>
        internal static string AddNewiSuraHeader {
            get {
                return ResourceManager.GetString("AddNewiSuraHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Verse to this Sura.
        /// </summary>
        internal static string AddNewiVerseHeader {
            get {
                return ResourceManager.GetString("AddNewiVerseHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quran Manager.
        /// </summary>
        internal static string AdminMenuiQuranManagerAdminLink {
            get {
                return ResourceManager.GetString("AdminMenuiQuranManagerAdminLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sura Manager.
        /// </summary>
        internal static string AdminMenuiSuraManagerAdminLink {
            get {
                return ResourceManager.GetString("AdminMenuiSuraManagerAdminLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verse Manager.
        /// </summary>
        internal static string AdminMenuiVerseManagerAdminLink {
            get {
                return ResourceManager.GetString("AdminMenuiVerseManagerAdminLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shine for All Advanced.
        /// </summary>
        internal static string AdvancedLink {
            get {
                return ResourceManager.GetString("AdvancedLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced Search Page.
        /// </summary>
        internal static string AdvancedSearchPageTitle {
            get {
                return ResourceManager.GetString("AdvancedSearchPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shine for All Administration.
        /// </summary>
        internal static string AdvancedToolsHeading {
            get {
                return ResourceManager.GetString("AdvancedToolsHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy All Remembered.
        /// </summary>
        internal static string CopyAllRemebered {
            get {
                return ResourceManager.GetString("CopyAllRemebered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created Date.
        /// </summary>
        internal static string CreatedDateHeader {
            get {
                return ResourceManager.GetString("CreatedDateHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string DescriptionHeader {
            get {
                return ResourceManager.GetString("DescriptionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit iQuran Version.
        /// </summary>
        internal static string EditiQuranHeader {
            get {
                return ResourceManager.GetString("EditiQuranHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit iSura Version.
        /// </summary>
        internal static string EditiSuraHeader {
            get {
                return ResourceManager.GetString("EditiSuraHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit iVerse Version.
        /// </summary>
        internal static string EditiVerseHeader {
            get {
                return ResourceManager.GetString("EditiVerseHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Half No.
        /// </summary>
        internal static string HalfNoHeader {
            get {
                return ResourceManager.GetString("HalfNoHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hizb No.
        /// </summary>
        internal static string HizbNoHeader {
            get {
                return ResourceManager.GetString("HizbNoHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iQuran Advanced.
        /// </summary>
        internal static string iQuranAdvancedToolsHeading {
            get {
                return ResourceManager.GetString("iQuranAdvancedToolsHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quran Version.
        /// </summary>
        internal static string iQuranHeader {
            get {
                return ResourceManager.GetString("iQuranHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Default.
        /// </summary>
        internal static string IsDefaultHeader {
            get {
                return ResourceManager.GetString("IsDefaultHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string LanguageHeader {
            get {
                return ResourceManager.GetString("LanguageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language of Version.
        /// </summary>
        internal static string LanguageofVersionHeader {
            get {
                return ResourceManager.GetString("LanguageofVersionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shine for All Library Advanced.
        /// </summary>
        internal static string LibraryAdvancedLink {
            get {
                return ResourceManager.GetString("LibraryAdvancedLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shine for All Library Administration.
        /// </summary>
        internal static string LibraryAdvancedToolsHeading {
            get {
                return ResourceManager.GetString("LibraryAdvancedToolsHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not active.
        /// </summary>
        internal static string NotActiveHeader {
            get {
                return ResourceManager.GetString("NotActiveHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        internal static string Number {
            get {
                return ResourceManager.GetString("Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Othmani Verse Text.
        /// </summary>
        internal static string OthmaniTextHeader {
            get {
                return ResourceManager.GetString("OthmaniTextHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results per Page.
        /// </summary>
        internal static string PageSize {
            get {
                return ResourceManager.GetString("PageSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part.
        /// </summary>
        internal static string PartHeader {
            get {
                return ResourceManager.GetString("PartHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part Number.
        /// </summary>
        internal static string PartNoHeader {
            get {
                return ResourceManager.GetString("PartNoHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sura Place.
        /// </summary>
        internal static string PlaceHeader {
            get {
                return ResourceManager.GetString("PlaceHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qurater No.
        /// </summary>
        internal static string QuraterNoHeader {
            get {
                return ResourceManager.GetString("QuraterNoHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remebered Verses.
        /// </summary>
        internal static string RemeberedVersesHeader {
            get {
                return ResourceManager.GetString("RemeberedVersesHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search By Word / Word Part Verse Part.
        /// </summary>
        internal static string SearchByPartHeader {
            get {
                return ResourceManager.GetString("SearchByPartHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search By Title / Title Part.
        /// </summary>
        internal static string SearchByTitleHeader {
            get {
                return ResourceManager.GetString("SearchByTitleHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End to Sura.
        /// </summary>
        internal static string SearchEndSura {
            get {
                return ResourceManager.GetString("SearchEndSura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End to Verse.
        /// </summary>
        internal static string SearchEndVerse {
            get {
                return ResourceManager.GetString("SearchEndVerse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search For.
        /// </summary>
        internal static string SearchFor {
            get {
                return ResourceManager.GetString("SearchFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for Word / Senetence.
        /// </summary>
        internal static string SearchForWordSenetence {
            get {
                return ResourceManager.GetString("SearchForWordSenetence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change all types of Alif&apos;s to &quot;ا&quot;.
        /// </summary>
        internal static string SearchNMAlif {
            get {
                return ResourceManager.GetString("SearchNMAlif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start From Sura.
        /// </summary>
        internal static string SearchStartFromSura {
            get {
                return ResourceManager.GetString("SearchStartFromSura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start From Verse.
        /// </summary>
        internal static string SearchStartFromVerse {
            get {
                return ResourceManager.GetString("SearchStartFromVerse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wanted Word.
        /// </summary>
        internal static string SearchWantedWord {
            get {
                return ResourceManager.GetString("SearchWantedWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Word Criteria.
        /// </summary>
        internal static string SearchWordCriteria {
            get {
                return ResourceManager.GetString("SearchWordCriteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font Type.
        /// </summary>
        internal static string SearchWordFontType {
            get {
                return ResourceManager.GetString("SearchWordFontType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search using Text or Select Root word ?.
        /// </summary>
        internal static string SearchWordTextOrRootType {
            get {
                return ResourceManager.GetString("SearchWordTextOrRootType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sellect All.
        /// </summary>
        internal static string SelectAllHeader {
            get {
                return ResourceManager.GetString("SelectAllHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select by Status.
        /// </summary>
        internal static string SelectByStatusLabel {
            get {
                return ResourceManager.GetString("SelectByStatusLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Half No.
        /// </summary>
        internal static string SelectHalfNoHeader {
            get {
                return ResourceManager.GetString("SelectHalfNoHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a Quran Version.
        /// </summary>
        internal static string SelectiQuran {
            get {
                return ResourceManager.GetString("SelectiQuran", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Sure.
        /// </summary>
        internal static string SelectiSura {
            get {
                return ResourceManager.GetString("SelectiSura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Sura Place.
        /// </summary>
        internal static string SelectPlaceHeader {
            get {
                return ResourceManager.GetString("SelectPlaceHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Root Word.
        /// </summary>
        internal static string SelectRoot {
            get {
                return ResourceManager.GetString("SelectRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        internal static string SeperatorDash {
            get {
                return ResourceManager.GetString("SeperatorDash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simple Search Page Results.
        /// </summary>
        internal static string SimpleSearchPageResultTitle {
            get {
                return ResourceManager.GetString("SimpleSearchPageResultTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simple Search Page.
        /// </summary>
        internal static string SimpleSearchPageTitle {
            get {
                return ResourceManager.GetString("SimpleSearchPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort Order.
        /// </summary>
        internal static string SortOrderHeader {
            get {
                return ResourceManager.GetString("SortOrderHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *.
        /// </summary>
        internal static string StarLabel {
            get {
                return ResourceManager.GetString("StarLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Sura Count.
        /// </summary>
        internal static string SuraCountHeader {
            get {
                return ResourceManager.GetString("SuraCountHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sura.
        /// </summary>
        internal static string SuraHeader {
            get {
                return ResourceManager.GetString("SuraHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sura Sort Order.
        /// </summary>
        internal static string SuraSortOrderHeader {
            get {
                return ResourceManager.GetString("SuraSortOrderHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sura.
        /// </summary>
        internal static string SuratHeader {
            get {
                return ResourceManager.GetString("SuratHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string TitleHeader {
            get {
                return ResourceManager.GetString("TitleHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translation.
        /// </summary>
        internal static string TranslationHeader {
            get {
                return ResourceManager.GetString("TranslationHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder of Translation.
        /// </summary>
        internal static string TranslationSrcHeader {
            get {
                return ResourceManager.GetString("TranslationSrcHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translator details.
        /// </summary>
        internal static string TRanslatorDetUrlHeader {
            get {
                return ResourceManager.GetString("TRanslatorDetUrlHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verse.
        /// </summary>
        internal static string VerseHeader {
            get {
                return ResourceManager.GetString("VerseHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verses Count.
        /// </summary>
        internal static string VersesCountHeader {
            get {
                return ResourceManager.GetString("VersesCountHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verse Sort Order.
        /// </summary>
        internal static string VerseSortOrderHeader {
            get {
                return ResourceManager.GetString("VerseSortOrderHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verse Text No Marks &amp; No Alif Marks.
        /// </summary>
        internal static string VerseTextNMAlifHeader {
            get {
                return ResourceManager.GetString("VerseTextNMAlifHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verse Text No Marks.
        /// </summary>
        internal static string VerseTextNMHeader {
            get {
                return ResourceManager.GetString("VerseTextNMHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Whole Sura.
        /// </summary>
        internal static string ViewWholeSura {
            get {
                return ResourceManager.GetString("ViewWholeSura", resourceCulture);
            }
        }
    }
}
