//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class iQuranOptionsResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal iQuranOptionsResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.iQuranOptionsResources", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string OptionHalfNoFirst {
            get {
                return ResourceManager.GetString("OptionHalfNoFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        internal static string OptionHalfNoSecond {
            get {
                return ResourceManager.GetString("OptionHalfNoSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Half Quran No.
        /// </summary>
        internal static string OptionHalfNoSelectHalfNo {
            get {
                return ResourceManager.GetString("OptionHalfNoSelectHalfNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Madeena.
        /// </summary>
        internal static string OptionPlaceMadeenaText {
            get {
                return ResourceManager.GetString("OptionPlaceMadeenaText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Madeena.
        /// </summary>
        internal static string OptionPlaceMadeenaValue {
            get {
                return ResourceManager.GetString("OptionPlaceMadeenaValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mekka.
        /// </summary>
        internal static string OptionPlaceMekkaText {
            get {
                return ResourceManager.GetString("OptionPlaceMekkaText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mekka.
        /// </summary>
        internal static string OptionPlaceMekkaValue {
            get {
                return ResourceManager.GetString("OptionPlaceMekkaValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Sura Place.
        /// </summary>
        internal static string OptionPlaceSelectPlace {
            get {
                return ResourceManager.GetString("OptionPlaceSelectPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part From Verse.
        /// </summary>
        internal static string OptionSearchedTextTypePartFromVerseText {
            get {
                return ResourceManager.GetString("OptionSearchedTextTypePartFromVerseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v.
        /// </summary>
        internal static string OptionSearchedTextTypePartFromVerseValue {
            get {
                return ResourceManager.GetString("OptionSearchedTextTypePartFromVerseValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part From Word.
        /// </summary>
        internal static string OptionSearchedTextTypePartFromWordText {
            get {
                return ResourceManager.GetString("OptionSearchedTextTypePartFromWordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to p.
        /// </summary>
        internal static string OptionSearchedTextTypePartFromWordValue {
            get {
                return ResourceManager.GetString("OptionSearchedTextTypePartFromWordValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Searched Text Type.
        /// </summary>
        internal static string OptionSearchedTextTypeSelect {
            get {
                return ResourceManager.GetString("OptionSearchedTextTypeSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Independent.
        /// </summary>
        internal static string OptionSearchedTextTypeStandAloneText {
            get {
                return ResourceManager.GetString("OptionSearchedTextTypeStandAloneText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to i.
        /// </summary>
        internal static string OptionSearchedTextTypeStandAloneValue {
            get {
                return ResourceManager.GetString("OptionSearchedTextTypeStandAloneValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dictional Font.
        /// </summary>
        internal static string OptionSearchFontTypeDictionalText {
            get {
                return ResourceManager.GetString("OptionSearchFontTypeDictionalText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TypeDict.
        /// </summary>
        internal static string OptionSearchFontTypeDictionalValue {
            get {
                return ResourceManager.GetString("OptionSearchFontTypeDictionalValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Othmani Font.
        /// </summary>
        internal static string OptionSearchFontTypeOthmaniText {
            get {
                return ResourceManager.GetString("OptionSearchFontTypeOthmaniText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TypeOthm.
        /// </summary>
        internal static string OptionSearchFontTypeOthmaniValue {
            get {
                return ResourceManager.GetString("OptionSearchFontTypeOthmaniValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dictional text with no Harakat  &amp; ignore Hamzat.
        /// </summary>
        internal static string OptionSearchWordCriteriaWordDictationalNMAlifText {
            get {
                return ResourceManager.GetString("OptionSearchWordCriteriaWordDictationalNMAlifText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DictNMAlif.
        /// </summary>
        internal static string OptionSearchWordCriteriaWordDictationalNMAlifValue {
            get {
                return ResourceManager.GetString("OptionSearchWordCriteriaWordDictationalNMAlifValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dictional text with no Harakat.
        /// </summary>
        internal static string OptionSearchWordCriteriaWordDictationalNMText {
            get {
                return ResourceManager.GetString("OptionSearchWordCriteriaWordDictationalNMText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DictNM.
        /// </summary>
        internal static string OptionSearchWordCriteriaWordDictationalNMValue {
            get {
                return ResourceManager.GetString("OptionSearchWordCriteriaWordDictationalNMValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Othmani text with no Harakat &amp; ignore Hamzat.
        /// </summary>
        internal static string OptionSearchWordCriteriaWordOthmaniNMAlifText {
            get {
                return ResourceManager.GetString("OptionSearchWordCriteriaWordOthmaniNMAlifText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OthmNMAlif.
        /// </summary>
        internal static string OptionSearchWordCriteriaWordOthmaniNMAlifValue {
            get {
                return ResourceManager.GetString("OptionSearchWordCriteriaWordOthmaniNMAlifValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Othmani text with no Harakat.
        /// </summary>
        internal static string OptionSearchWordCriteriaWordOthmaniNMText {
            get {
                return ResourceManager.GetString("OptionSearchWordCriteriaWordOthmaniNMText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OthmNM.
        /// </summary>
        internal static string OptionSearchWordCriteriaWordOthmaniNMValue {
            get {
                return ResourceManager.GetString("OptionSearchWordCriteriaWordOthmaniNMValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Othmani Text.
        /// </summary>
        internal static string OptionSearchWordCriteriaWordOthmaniText {
            get {
                return ResourceManager.GetString("OptionSearchWordCriteriaWordOthmaniText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Othm.
        /// </summary>
        internal static string OptionSearchWordCriteriaWordOthmaniValue {
            get {
                return ResourceManager.GetString("OptionSearchWordCriteriaWordOthmaniValue", resourceCulture);
            }
        }
    }
}
