//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class iQuranMessagesResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal iQuranMessagesResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.iQuranMessagesResources", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This page is designed for Advanced Search by many criterias.
        /// </summary>
        internal static string AdvancedSearchInfo {
            get {
                return ResourceManager.GetString("AdvancedSearchInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Item deleted succsessfully !.
        /// </summary>
        internal static string DeletedMsg {
            get {
                return ResourceManager.GetString("DeletedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete this version of Quran and all related to it data !.
        /// </summary>
        internal static string DeleteQuranTip {
            get {
                return ResourceManager.GetString("DeleteQuranTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this Version of Quran ? this will delete all related to it Suras and Verses if exists !!.
        /// </summary>
        internal static string DeleteQuranWarning {
            get {
                return ResourceManager.GetString("DeleteQuranWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete this Sura and all related to it Verses !.
        /// </summary>
        internal static string DeleteSuraTip {
            get {
                return ResourceManager.GetString("DeleteSuraTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this Sura ? this will delete all related to it Verses if exists !!.
        /// </summary>
        internal static string DeleteSuraWarning {
            get {
                return ResourceManager.GetString("DeleteSuraWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete this Verses !.
        /// </summary>
        internal static string DeleteVerseTip {
            get {
                return ResourceManager.GetString("DeleteVerseTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this Verse ?!.
        /// </summary>
        internal static string DeleteVerseWarning {
            get {
                return ResourceManager.GetString("DeleteVerseWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this Version of Quran ? this will delete all related to it sub Items if exists !!.
        /// </summary>
        internal static string DeleteWarning {
            get {
                return ResourceManager.GetString("DeleteWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fialed to delete the Item ! Please Try Later !.
        /// </summary>
        internal static string FailedDelete {
            get {
                return ResourceManager.GetString("FailedDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fialed to save the Item ! Please Try Later !.
        /// </summary>
        internal static string FailedSave {
            get {
                return ResourceManager.GetString("FailedSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is some error happened, please try later!.
        /// </summary>
        internal static string HelpNoVerseAvailable {
            get {
                return ResourceManager.GetString("HelpNoVerseAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no Data entered yet !.
        /// </summary>
        internal static string NoDataYet {
            get {
                return ResourceManager.GetString("NoDataYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no reults found!.
        /// </summary>
        internal static string NoSearchResult {
            get {
                return ResourceManager.GetString("NoSearchResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Size - Results in one page - are limited from 1 -100.
        /// </summary>
        internal static string PageSizeLimit {
            get {
                return ResourceManager.GetString("PageSizeLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quran Description is Required !.
        /// </summary>
        internal static string QuranDescriptionRequired {
            get {
                return ResourceManager.GetString("QuranDescriptionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quran Language is Required !.
        /// </summary>
        internal static string QuranLanguageRequired {
            get {
                return ResourceManager.GetString("QuranLanguageRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required.
        /// </summary>
        internal static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Text Required!.
        /// </summary>
        internal static string SearchTextsRequired {
            get {
                return ResourceManager.GetString("SearchTextsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verses numbers limited from 1 to 286.
        /// </summary>
        internal static string SearchVerseFromToLimit {
            get {
                return ResourceManager.GetString("SearchVerseFromToLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This page is designed for Simple Search by word / sentence of the verses.
        /// </summary>
        internal static string SimpleSearchInfo {
            get {
                return ResourceManager.GetString("SimpleSearchInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Item deleted succsessfully !.
        /// </summary>
        internal static string SuccessfullDelete {
            get {
                return ResourceManager.GetString("SuccessfullDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Item saved succsessfully !.
        /// </summary>
        internal static string SuccessfullSave {
            get {
                return ResourceManager.GetString("SuccessfullSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Order was taken to another Sura, it is Exists !.
        /// </summary>
        internal static string SuraOrderExists {
            get {
                return ResourceManager.GetString("SuraOrderExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is not allowed to add space or another word when you search for &quot;Only Word&quot; or &quot;Part from Word&quot; !.
        /// </summary>
        internal static string TextSearchSpacesNotAllowed {
            get {
                return ResourceManager.GetString("TextSearchSpacesNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Title Exists !.
        /// </summary>
        internal static string TitleExists {
            get {
                return ResourceManager.GetString("TitleExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title is Required !.
        /// </summary>
        internal static string TitleRequired {
            get {
                return ResourceManager.GetString("TitleRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UNDER CONSTRUCTION !.
        /// </summary>
        internal static string UnderConstruction {
            get {
                return ResourceManager.GetString("UnderConstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Verse Exists !.
        /// </summary>
        internal static string VerseExists {
            get {
                return ResourceManager.GetString("VerseExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no such ORDER in the Original Quran for this verse!!.
        /// </summary>
        internal static string VerseNoSuchOrder {
            get {
                return ResourceManager.GetString("VerseNoSuchOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Order was taken to another Verse, it is Exists !.
        /// </summary>
        internal static string VerseOrderExists {
            get {
                return ResourceManager.GetString("VerseOrderExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verse Texts (All Types of text) is Required !.
        /// </summary>
        internal static string VerseTextsRequired {
            get {
                return ResourceManager.GetString("VerseTextsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verse Translation is Required !.
        /// </summary>
        internal static string VerseTranslationRequired {
            get {
                return ResourceManager.GetString("VerseTranslationRequired", resourceCulture);
            }
        }
    }
}
