//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LanguagesResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LanguagesResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.LanguagesResources", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afrikaans.
        /// </summary>
        internal static string LanguageLabelAfrikaans {
            get {
                return ResourceManager.GetString("LanguageLabelAfrikaans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Albanian.
        /// </summary>
        internal static string LanguageLabelAlbanian {
            get {
                return ResourceManager.GetString("LanguageLabelAlbanian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic.
        /// </summary>
        internal static string LanguageLabelArabic {
            get {
                return ResourceManager.GetString("LanguageLabelArabic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basque.
        /// </summary>
        internal static string LanguageLabelBasque {
            get {
                return ResourceManager.GetString("LanguageLabelBasque", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Belarusian.
        /// </summary>
        internal static string LanguageLabelBelarusian {
            get {
                return ResourceManager.GetString("LanguageLabelBelarusian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bulgarian.
        /// </summary>
        internal static string LanguageLabelBulgarian {
            get {
                return ResourceManager.GetString("LanguageLabelBulgarian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chinese.
        /// </summary>
        internal static string LanguageLabelChinese {
            get {
                return ResourceManager.GetString("LanguageLabelChinese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Croatian.
        /// </summary>
        internal static string LanguageLabelCroatian {
            get {
                return ResourceManager.GetString("LanguageLabelCroatian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czech.
        /// </summary>
        internal static string LanguageLabelCzech {
            get {
                return ResourceManager.GetString("LanguageLabelCzech", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danish.
        /// </summary>
        internal static string LanguageLabelDanish {
            get {
                return ResourceManager.GetString("LanguageLabelDanish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dutch.
        /// </summary>
        internal static string LanguageLabelDutch {
            get {
                return ResourceManager.GetString("LanguageLabelDutch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string LanguageLabelEnglish {
            get {
                return ResourceManager.GetString("LanguageLabelEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estonian.
        /// </summary>
        internal static string LanguageLabelEstonian {
            get {
                return ResourceManager.GetString("LanguageLabelEstonian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Farsi.
        /// </summary>
        internal static string LanguageLabelFarsi {
            get {
                return ResourceManager.GetString("LanguageLabelFarsi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finnish.
        /// </summary>
        internal static string LanguageLabelFinnish {
            get {
                return ResourceManager.GetString("LanguageLabelFinnish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to French.
        /// </summary>
        internal static string LanguageLabelFrench {
            get {
                return ResourceManager.GetString("LanguageLabelFrench", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gaelic.
        /// </summary>
        internal static string LanguageLabelGaelic {
            get {
                return ResourceManager.GetString("LanguageLabelGaelic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to German.
        /// </summary>
        internal static string LanguageLabelGerman {
            get {
                return ResourceManager.GetString("LanguageLabelGerman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greek.
        /// </summary>
        internal static string LanguageLabelGreek {
            get {
                return ResourceManager.GetString("LanguageLabelGreek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hebrew.
        /// </summary>
        internal static string LanguageLabelHebrew {
            get {
                return ResourceManager.GetString("LanguageLabelHebrew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hindi.
        /// </summary>
        internal static string LanguageLabelHindi {
            get {
                return ResourceManager.GetString("LanguageLabelHindi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hungarian.
        /// </summary>
        internal static string LanguageLabelHungarian {
            get {
                return ResourceManager.GetString("LanguageLabelHungarian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icelandic.
        /// </summary>
        internal static string LanguageLabelIcelandic {
            get {
                return ResourceManager.GetString("LanguageLabelIcelandic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indonesian.
        /// </summary>
        internal static string LanguageLabelIndonesian {
            get {
                return ResourceManager.GetString("LanguageLabelIndonesian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Irish.
        /// </summary>
        internal static string LanguageLabelIrish {
            get {
                return ResourceManager.GetString("LanguageLabelIrish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Italian.
        /// </summary>
        internal static string LanguageLabelItalian {
            get {
                return ResourceManager.GetString("LanguageLabelItalian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Japanese.
        /// </summary>
        internal static string LanguageLabelJapanese {
            get {
                return ResourceManager.GetString("LanguageLabelJapanese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korean.
        /// </summary>
        internal static string LanguageLabelKorean {
            get {
                return ResourceManager.GetString("LanguageLabelKorean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latvian.
        /// </summary>
        internal static string LanguageLabelLatvian {
            get {
                return ResourceManager.GetString("LanguageLabelLatvian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lithuanian.
        /// </summary>
        internal static string LanguageLabelLithuanian {
            get {
                return ResourceManager.GetString("LanguageLabelLithuanian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Macedonian.
        /// </summary>
        internal static string LanguageLabelMacedonian {
            get {
                return ResourceManager.GetString("LanguageLabelMacedonian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Malaysian.
        /// </summary>
        internal static string LanguageLabelMalaysian {
            get {
                return ResourceManager.GetString("LanguageLabelMalaysian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maltese.
        /// </summary>
        internal static string LanguageLabelMaltese {
            get {
                return ResourceManager.GetString("LanguageLabelMaltese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Norwegian.
        /// </summary>
        internal static string LanguageLabelNorwegian {
            get {
                return ResourceManager.GetString("LanguageLabelNorwegian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polish.
        /// </summary>
        internal static string LanguageLabelPolish {
            get {
                return ResourceManager.GetString("LanguageLabelPolish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portuguese.
        /// </summary>
        internal static string LanguageLabelPortuguese {
            get {
                return ResourceManager.GetString("LanguageLabelPortuguese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Romanian.
        /// </summary>
        internal static string LanguageLabelRomanian {
            get {
                return ResourceManager.GetString("LanguageLabelRomanian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Russian.
        /// </summary>
        internal static string LanguageLabelRussian {
            get {
                return ResourceManager.GetString("LanguageLabelRussian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Language.
        /// </summary>
        internal static string LanguageLabelSelectLanguage {
            get {
                return ResourceManager.GetString("LanguageLabelSelectLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slovak.
        /// </summary>
        internal static string LanguageLabelSlovak {
            get {
                return ResourceManager.GetString("LanguageLabelSlovak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slovenian.
        /// </summary>
        internal static string LanguageLabelSlovenian {
            get {
                return ResourceManager.GetString("LanguageLabelSlovenian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorbian.
        /// </summary>
        internal static string LanguageLabelSorbian {
            get {
                return ResourceManager.GetString("LanguageLabelSorbian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spanish.
        /// </summary>
        internal static string LanguageLabelSpanish {
            get {
                return ResourceManager.GetString("LanguageLabelSpanish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swedish.
        /// </summary>
        internal static string LanguageLabelSwedish {
            get {
                return ResourceManager.GetString("LanguageLabelSwedish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thai.
        /// </summary>
        internal static string LanguageLabelThai {
            get {
                return ResourceManager.GetString("LanguageLabelThai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turkish.
        /// </summary>
        internal static string LanguageLabelTurkish {
            get {
                return ResourceManager.GetString("LanguageLabelTurkish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ukrainian.
        /// </summary>
        internal static string LanguageLabelUkrainian {
            get {
                return ResourceManager.GetString("LanguageLabelUkrainian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Urdu.
        /// </summary>
        internal static string LanguageLabelUrdu {
            get {
                return ResourceManager.GetString("LanguageLabelUrdu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vietnamese.
        /// </summary>
        internal static string LanguageLabelVietnamese {
            get {
                return ResourceManager.GetString("LanguageLabelVietnamese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yiddish.
        /// </summary>
        internal static string LanguageLabelYiddish {
            get {
                return ResourceManager.GetString("LanguageLabelYiddish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zulu.
        /// </summary>
        internal static string LanguageLabelZulu {
            get {
                return ResourceManager.GetString("LanguageLabelZulu", resourceCulture);
            }
        }
    }
}
